### ISSUE TITLE
Automated "Deploy" Button Missing

### ISSUE THREAD

**Issue by matt-morrell** [Azure/cortana-intelligence-price-optimization#11]
The automated deploy method references a "deploy" button that appears to be missing.

**Comment by lericha** [comment]
Matt - the Cortana Quickstart service has been deprecated and the 'Deploy with a single click' feature is apparently gone with no replacement in sight.  Manual deployments only now.  There is, however, the possibility of the Quickstart Templates working:
https://github.com/Azure/azure-quickstart-templates

Good luck with it, this has caused a serious bump in the road for some workshop IP.

**Comment by praneet22** [comment]
The platform to support automated deployment is deprecated, manual deployment is the only possible way to deploy the solution.
